[changelog]
header = "# Changelog\n\n"
body = """
## {% if version %}{{ version | trim_start_matches(pat="v") }}{% else %}[Unreleased]{% endif %}

{% for commit in commits -%}
- {% if commit.breaking %}Breaking change: {% endif %}{{ commit.message | upper_first }}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
  { message = "^feat", group = "kept" },
  { message = "^fix", group = "kept" },
  { message = "^perf", group = "kept" },
  { message = ".*!:", group = "kept" },
  { message = ".*", skip = true },
]
filter_commits = true
topo_order = false
sort_commits = "newest"
