// IMPLEMENTS: D-340
//! Per-jurisdiction legal disclosure auto-trigger.
//!
//! 2026 stacked AI laws — EU AI Act (Aug), Colorado AI Consumer Act (Jun),
//! Illinois AI Bias law (Jan), California SB-942 (Jan) — each demand a
//! disclosure under different conditions. We bind each skill's
//! `risk_tier` and `applicable_jurisdictions` to canned text so the
//! daemon never has to compose a notice on the fly.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Jurisdiction {
    EuAiAct,
    UsCa,
    UsCo,
    UsIl,
    Kr,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RiskTier {
    Minimal,
    Limited,
    HighRisk,
    Prohibited,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SkillMeta {
    pub risk_tier: RiskTier,
    pub applicable_jurisdictions: Vec<Jurisdiction>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LegalDisclosure {
    pub jurisdiction: Jurisdiction,
    pub citation: &'static str,
    pub body: &'static str,
}

#[must_use]
pub fn disclosures_for(meta: &SkillMeta, user_jurisdiction: Jurisdiction) -> Vec<LegalDisclosure> {
    if matches!(meta.risk_tier, RiskTier::Prohibited) {
        return vec![LegalDisclosure {
            jurisdiction: user_jurisdiction,
            citation: "harness/internal/prohibited",
            body: "This skill is classified Prohibited and is blocked from execution.",
        }];
    }
    if !meta.applicable_jurisdictions.contains(&user_jurisdiction) {
        return Vec::new();
    }
    let mut out = Vec::new();
    match (user_jurisdiction, meta.risk_tier) {
        (Jurisdiction::EuAiAct, RiskTier::HighRisk) => out.push(LegalDisclosure {
            jurisdiction: Jurisdiction::EuAiAct,
            citation: "EU AI Act 2024/1689 Art 50 + Annex III",
            body: "This output was produced by a high-risk AI system. You may request human review under EU AI Act Art 14.",
        }),
        (Jurisdiction::EuAiAct, _) => out.push(LegalDisclosure {
            jurisdiction: Jurisdiction::EuAiAct,
            citation: "EU AI Act 2024/1689 Art 50",
            body: "This content was generated by an automated system.",
        }),
        (Jurisdiction::UsCa, _) => out.push(LegalDisclosure {
            jurisdiction: Jurisdiction::UsCa,
            citation: "California SB-942",
            body: "[AI generated] This message was produced by an automated chatbot.",
        }),
        (Jurisdiction::UsCo, RiskTier::HighRisk) => out.push(LegalDisclosure {
            jurisdiction: Jurisdiction::UsCo,
            citation: "Colorado SB24-205",
            body: "An automated system contributed to this consequential decision. You have the right to be told the principal factors and to appeal.",
        }),
        (Jurisdiction::UsIl, RiskTier::HighRisk) => out.push(LegalDisclosure {
            jurisdiction: Jurisdiction::UsIl,
            citation: "Illinois HB 3773 (Aug 2026)",
            body: "An automated system was used in this employment-adjacent decision. Discriminatory outcomes are prohibited under Illinois law.",
        }),
        (Jurisdiction::Kr, RiskTier::HighRisk) => out.push(LegalDisclosure {
            jurisdiction: Jurisdiction::Kr,
            citation: "한국 AI 기본법 (2024)",
            body: "이 결과는 고영향 AI 시스템이 생성했으며, 사용자는 사람 검토를 요청할 수 있습니다.",
        }),
        _ => {}
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn meta(tier: RiskTier, jurisdictions: Vec<Jurisdiction>) -> SkillMeta {
        SkillMeta {
            risk_tier: tier,
            applicable_jurisdictions: jurisdictions,
        }
    }

    #[test]
    fn prohibited_tier_blocks_regardless_of_jurisdiction_overlap() {
        let m = meta(RiskTier::Prohibited, vec![]);
        let d = disclosures_for(&m, Jurisdiction::UsCa);
        assert_eq!(d.len(), 1);
        assert!(d[0].body.contains("Prohibited"));
    }

    #[test]
    fn no_jurisdiction_overlap_returns_empty() {
        let m = meta(RiskTier::Limited, vec![Jurisdiction::Kr]);
        assert!(disclosures_for(&m, Jurisdiction::UsCa).is_empty());
    }

    #[test]
    fn eu_high_risk_cites_art_14() {
        let m = meta(RiskTier::HighRisk, vec![Jurisdiction::EuAiAct]);
        let d = disclosures_for(&m, Jurisdiction::EuAiAct);
        assert!(d.iter().any(|x| x.body.contains("Art 14")));
    }

    #[test]
    fn ca_short_notice_uses_sb_942() {
        let m = meta(RiskTier::Limited, vec![Jurisdiction::UsCa]);
        let d = disclosures_for(&m, Jurisdiction::UsCa);
        assert!(d.iter().any(|x| x.citation.contains("SB-942")));
    }

    #[test]
    fn colorado_high_risk_cites_sb24_205() {
        let m = meta(RiskTier::HighRisk, vec![Jurisdiction::UsCo]);
        let d = disclosures_for(&m, Jurisdiction::UsCo);
        assert!(d.iter().any(|x| x.citation.contains("SB24-205")));
    }

    #[test]
    fn kr_high_risk_emits_korean_text() {
        let m = meta(RiskTier::HighRisk, vec![Jurisdiction::Kr]);
        let d = disclosures_for(&m, Jurisdiction::Kr);
        assert!(d.iter().any(|x| x.body.contains("AI 시스템")));
    }
}
