// IMPLEMENTS: D-111, D-116
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use thiserror::Error;

pub const DEFAULT_VCPUS: u8 = 1;
pub const DEFAULT_MEMORY_MB: u32 = 512;
pub const DEFAULT_DISK_GB: u32 = 5;

#[derive(Debug, Error)]
pub enum LimaError {
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    #[error("vm image hash mismatch: expected {expected}, got {actual}")]
    ImageHashMismatch { expected: String, actual: String },
    #[error("vm socket {path} has insecure mode {mode:o}; expected 0600")]
    InsecureSocket { path: PathBuf, mode: u32 },
    #[error("missing vm image: {0}")]
    MissingImage(PathBuf),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LimaConfig {
    pub vcpus: u8,
    pub memory_mb: u32,
    pub disk_gb: u32,
    pub mount_root: PathBuf,
    pub image_path: PathBuf,
    pub image_sha256: String,
    pub socket_path: PathBuf,
}

impl LimaConfig {
    /// Pinned defaults from D-111: 1 vCPU · 512MB · 5GB.
    #[must_use]
    pub fn pinned(image_path: PathBuf, image_sha256: String, mount_root: PathBuf) -> Self {
        let socket_path = mount_root.join("lima.sock");
        Self {
            vcpus: DEFAULT_VCPUS,
            memory_mb: DEFAULT_MEMORY_MB,
            disk_gb: DEFAULT_DISK_GB,
            mount_root,
            image_path,
            image_sha256,
            socket_path,
        }
    }

    /// Render the YAML Lima consumes — encodes D-116 invariants:
    /// read-only virtiofs mount, no host networks beyond loopback.
    #[must_use]
    pub fn to_yaml(&self) -> String {
        let mut s = String::with_capacity(512);
        s.push_str("# generated by harness-runtime-lima — do not edit\n");
        s.push_str(&format!("cpus: {}\n", self.vcpus));
        s.push_str(&format!("memory: \"{}MiB\"\n", self.memory_mb));
        s.push_str(&format!("disk: \"{}GiB\"\n", self.disk_gb));
        s.push_str(&format!(
            "images:\n  - location: \"{}\"\n",
            display(&self.image_path)
        ));
        s.push_str("mounts:\n");
        s.push_str(&format!(
            "  - location: \"{}\"\n    writable: false\n    9p:\n      cache: never\n    virtiofs:\n      queueSize: 1024\n",
            display(&self.mount_root)
        ));
        s.push_str("networks:\n");
        // D-116: VM loopback only. No bridged / host networks.
        s.push_str("  - lima: user-v2\n");
        s.push_str("portForwards:\n");
        s.push_str("  - guestIPMustBeZero: true\n");
        s.push_str("    hostIP: \"127.0.0.1\"\n");
        s.push_str("propagateProxyEnv: false\n");
        s.push_str(&format!("paramFile: \"{}\"\n", display(&self.socket_path)));
        s
    }
}

fn display(p: &Path) -> String {
    p.display().to_string()
}

/// Verify the on-disk VM image matches the manifest hash. Returns Ok if the
/// file is missing — the runtime will then refuse to start, which is the
/// right behaviour during initial install.
pub fn verify_image(image_path: &Path, expected_sha256: &str) -> Result<(), LimaError> {
    if !image_path.exists() {
        return Err(LimaError::MissingImage(image_path.to_path_buf()));
    }
    let bytes = std::fs::read(image_path)?;
    let actual = blake_hash_hex(&bytes);
    if actual != expected_sha256 {
        return Err(LimaError::ImageHashMismatch {
            expected: expected_sha256.into(),
            actual,
        });
    }
    Ok(())
}

fn blake_hash_hex(bytes: &[u8]) -> String {
    blake3::hash(bytes).to_hex().to_string()
}

/// On unix the socket file backing Lima must be owner-only (0600). Reject
/// anything more permissive — that is how a sibling user could pivot into
/// the VM and bypass the sandbox.
pub fn verify_socket_permissions(path: &Path) -> Result<(), LimaError> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if !path.exists() {
            return Ok(());
        }
        let mode = std::fs::metadata(path)?.permissions().mode() & 0o777;
        if mode != 0o600 {
            return Err(LimaError::InsecureSocket {
                path: path.to_path_buf(),
                mode,
            });
        }
    }
    #[cfg(not(unix))]
    {
        let _ = path;
    }
    Ok(())
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FallbackTrigger {
    SandboxExecMissing,
    SandboxExecSelfTestFailed,
    UserOptIn,
}

/// Decide whether to fall back to Lima after a self-test signal. Mirrors
/// D-111: any sandbox-exec failure (or explicit opt-in) escalates.
#[must_use]
pub fn should_fall_back(trigger: FallbackTrigger) -> bool {
    matches!(
        trigger,
        FallbackTrigger::SandboxExecMissing
            | FallbackTrigger::SandboxExecSelfTestFailed
            | FallbackTrigger::UserOptIn
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn dummy_config() -> LimaConfig {
        LimaConfig::pinned(
            PathBuf::from("/var/harness/vm.qcow2"),
            "feedface".into(),
            PathBuf::from("/var/harness"),
        )
    }

    #[test]
    fn defaults_are_pinned() {
        let c = dummy_config();
        assert_eq!(c.vcpus, 1);
        assert_eq!(c.memory_mb, 512);
        assert_eq!(c.disk_gb, 5);
        assert_eq!(c.socket_path, PathBuf::from("/var/harness/lima.sock"));
    }

    #[test]
    fn yaml_pins_writable_false_and_loopback_network() {
        let c = dummy_config();
        let y = c.to_yaml();
        assert!(y.contains("writable: false"), "must mount read-only");
        assert!(
            y.contains("hostIP: \"127.0.0.1\""),
            "must bind loopback only"
        );
        assert!(y.contains("cpus: 1"));
        assert!(y.contains("memory: \"512MiB\""));
        assert!(y.contains("disk: \"5GiB\""));
    }

    #[test]
    fn missing_image_is_an_error() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("absent.qcow2");
        let err = verify_image(&path, "0").unwrap_err();
        assert!(matches!(err, LimaError::MissingImage(_)), "got {err:?}");
    }

    #[test]
    fn image_hash_check_passes_when_match() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("image.bin");
        std::fs::write(&path, b"the bits").unwrap();
        let expected = blake_hash_hex(b"the bits");
        verify_image(&path, &expected).unwrap();
    }

    #[test]
    fn image_hash_check_rejects_tamper() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("image.bin");
        std::fs::write(&path, b"the bits").unwrap();
        let err = verify_image(&path, "deadbeef").unwrap_err();
        assert!(
            matches!(err, LimaError::ImageHashMismatch { .. }),
            "got {err:?}"
        );
    }

    #[cfg(unix)]
    #[test]
    fn socket_permissions_must_be_0600() {
        use std::os::unix::fs::PermissionsExt;
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("lima.sock");
        std::fs::write(&path, []).unwrap();
        let mut p = std::fs::metadata(&path).unwrap().permissions();
        p.set_mode(0o644);
        std::fs::set_permissions(&path, p).unwrap();
        let err = verify_socket_permissions(&path).unwrap_err();
        assert!(matches!(err, LimaError::InsecureSocket { .. }));
        let mut p = std::fs::metadata(&path).unwrap().permissions();
        p.set_mode(0o600);
        std::fs::set_permissions(&path, p).unwrap();
        verify_socket_permissions(&path).unwrap();
    }

    #[test]
    fn fallback_triggers_escalate() {
        assert!(should_fall_back(FallbackTrigger::SandboxExecMissing));
        assert!(should_fall_back(FallbackTrigger::SandboxExecSelfTestFailed));
        assert!(should_fall_back(FallbackTrigger::UserOptIn));
    }
}
